
services:

  selenium-hub:
    image: selenium/hub:4.15.0-20231122
    restart: unless-stopped
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:4.15.0-20231122
    shm_size: 2gb
    restart: unless-stopped
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_SESSION_TIMEOUT=30
      - SE_START_XVFB=false
      - SE_START_VNC=false
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=8
      - JAVA_OPTS=-XX:ActiveProcessorCount=8