services:

  nginxproxymanager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - 80:80
      - 127.0.0.1:81:81
      - 443:443
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    environment:
      - DB_MYSQL_HOST=db
      - DB_MYSQL_PORT=${DB_MYSQL_PORT}
      - DB_MYSQL_USER=${DB_MYSQL_USER}
      - DB_MYSQL_PASSWORD=${DB_MYSQL_PASSWORD}
      - DB_MYSQL_NAME=${DB_MYSQL_NAME}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - npm-data:/data
      - npm-ssl:/etc/letsencrypt
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MARIADB_AUTO_UPGRADE='1'
    volumes:
      - npm-db:/var/lib/mysql


volumes:
  npm-data:
  npm-ssl:
  npm-db: