global:
  scrape_interval: 15s

scrape_configs:

  # Make Prometheus scrape itself for metrics.
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
    - targets: ['prometheus:9090']

  # Node exporter metrics
  - job_name: 'node'
    static_configs:
    - targets: ['node-exporter:9100']

  # Others...

remote_write:
  - url: <Remote_IP>
    basic_auth:
      username: <username>
      password: <password>
